"""Probe FP16-sensitive layers in inswapper_128 via polygraphy bisection.

Why this script exists
----------------------
A naive `fp16=True` build of inswapper produces visibly garbled swap
output — TRT picks FP16 kernels for layers the inswapper graph is
sensitive about (instance norm, residual adds, etc.). The historical
fix was "build FP32 everywhere", which loses the FP16 perf win.

This script uses polygraphy's `debug precision` subtool to bisect:

    1. Patch inswapper_128.onnx for dynamic batch (same patch the
       runtime builder uses).
    2. Generate a golden ORT FP32 reference output for deterministic
       random inputs at the opt batch shape.
    3. Run `polygraphy debug precision --fp16 --precision-constraints
       obey --mode bisect --precision float32 --dir reverse` which
       iteratively marks layers (starting from network outputs) as
       FP32 until the engine's output matches the ORT golden within
       a configurable tolerance.
    4. On success, polygraphy leaves a `polygraphy_debug.engine` in
       the work dir. The script copies that engine to
       models/inswapper_128.engine.

The engine is a one-shot artifact for this GPU + TRT version. If you
upgrade TRT or change GPU, re-run this script. Note that clicking the
"Build TensorRT" button in the UI will OVERWRITE this engine with the
default FP32 build — re-run the probe afterward to get FP16 back.

Usage
-----
    venv\\Scripts\\python.exe -m rope.scripts.probe_inswapper_fp16

    Optional flags:
        --rtol 0.01        Per-element relative tolerance (default 0.01)
        --atol 0.01        Per-element absolute tolerance (default 0.01)
        --keep-workdir     Leave the temp build dir for inspection.
        --workdir PATH     Use this directory instead of a tmp one.

Expect 10-60 minutes depending on how many bisection iterations are
needed; each iteration rebuilds the full engine (~30s).
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent.parent


_DATA_LOADER_TEMPLATE = '''"""Auto-generated by rope.scripts.probe_inswapper_fp16.

Loads a real face pair as inswapper inputs:
  target = preprocessed 128x128 face chip (BGR->RGB, /255, NCHW float32)
  source = swapper-latent (ArcFace embedding -> emap projection -> L2-norm)

Polygraphy invokes load_data() and consumes the yielded dict as the
input for a single iteration. Both tensors are broadcast to BATCH rows
so the bisection check exercises the same shape as production polyphase.
"""
import numpy as np
import cv2
import onnx
import onnxruntime as ort

SOURCE_IMG = r"{SOURCE_IMG}"
TARGET_IMG = r"{TARGET_IMG}"
INSWAPPER_ONNX = r"{INSWAPPER_ONNX}"
ARCFACE_ONNX = r"{ARCFACE_ONNX}"
BATCH = {BATCH}


def _arcface_embedding(path):
    img = cv2.imread(path)
    if img is None:
        raise RuntimeError("failed to read " + path)
    # InsightFace ArcFace preprocessing: BGR, 112x112, (x - 127.5) / 127.5
    face = cv2.resize(img, (112, 112)).astype(np.float32)
    face = (face - 127.5) / 127.5
    face = face.transpose(2, 0, 1)[None, ...]
    sess = ort.InferenceSession(ARCFACE_ONNX, providers=["CPUExecutionProvider"])
    emb = sess.run(None, {{"input.1": face}})[0].reshape(-1)
    return emb.astype(np.float32)


def _swapper_latent(arcface_emb):
    # Reproduce Models.calc_swapper_latent: extract emap (the last
    # graph initializer in inswapper_128.onnx), project the L2-normalized
    # embedding through it, then renormalize. This is what production
    # passes as the inswapper "source" input — NOT the raw ArcFace
    # embedding.
    g = onnx.load(INSWAPPER_ONNX).graph
    emap = onnx.numpy_helper.to_array(g.initializer[-1])
    n_e = arcface_emb / np.linalg.norm(arcface_emb)
    latent = (n_e.reshape(1, -1) @ emap).reshape(-1)
    latent /= np.linalg.norm(latent)
    return latent.astype(np.float32)


def _target_blob(path):
    img = cv2.imread(path)
    if img is None:
        raise RuntimeError("failed to read " + path)
    # InsightFace inswapper preprocessing: 128x128, BGR->RGB, /255 (no
    # mean subtraction). Real production aligns the face via kps first;
    # we skip alignment because the bisection only needs realistic
    # numerical structure, not pixel-perfect identity.
    chip = cv2.resize(img, (128, 128))
    chip = cv2.cvtColor(chip, cv2.COLOR_BGR2RGB)
    chip = chip.astype(np.float32) / 255.0
    chip = chip.transpose(2, 0, 1)  # HWC -> CHW
    return chip


def load_data():
    target_chw = _target_blob(TARGET_IMG)
    source_emb = _arcface_embedding(SOURCE_IMG)
    source_latent = _swapper_latent(source_emb)

    target_batch = np.broadcast_to(
        target_chw, (BATCH, 3, 128, 128)
    ).copy().astype(np.float32)
    source_batch = np.broadcast_to(
        source_latent, (BATCH, 512)
    ).copy().astype(np.float32)
    yield {{"target": target_batch, "source": source_batch}}
'''


def _write_data_loader(out_path, source_img, target_img,
                      inswapper_onnx, arcface_onnx, batch):
    """Render the data-loader template with absolute paths baked in.
    Polygraphy imports this file in a subprocess so all paths must be
    self-contained."""
    out_path.write_text(_DATA_LOADER_TEMPLATE.format(
        SOURCE_IMG=str(Path(source_img).resolve()),
        TARGET_IMG=str(Path(target_img).resolve()),
        INSWAPPER_ONNX=str(Path(inswapper_onnx).resolve()),
        ARCFACE_ONNX=str(Path(arcface_onnx).resolve()),
        BATCH=int(batch),
    ), encoding='utf-8')


def _polygraphy_exe() -> str:
    """Locate the polygraphy CLI. The pip install adds polygraphy(.exe)
    next to the python executable in the venv's Scripts/bin dir. We
    derive from sys.executable so this works whether the venv is on
    PATH or not."""
    py = Path(sys.executable)
    candidates = [
        py.with_name('polygraphy.exe'),  # Windows venv
        py.with_name('polygraphy'),      # Linux / macOS venv
    ]
    for c in candidates:
        if c.is_file():
            return str(c)
    # Last resort: rely on PATH. Works if the venv is activated.
    return 'polygraphy'


def _patched_onnx_bytes(log) -> bytes:
    """Reuse the runtime builder's dynamic-batch patch so the probe
    engine has the same I/O shape semantics as the production engine."""
    from rope import TensorRTEngine as TRT
    log(f'[probe] patching {TRT.INSWAPPER_ONNX} for dynamic batch')
    return TRT._patch_inswapper_for_dynamic_batch(TRT.INSWAPPER_ONNX, log=log)


def _generate_golden(patched_onnx_path: Path, inputs_path: Path,
                     outputs_path: Path, opt_batch: int,
                     data_loader_path: Path | None, log) -> None:
    """Run the patched ONNX through ORT at opt batch size; save BOTH
    inputs and outputs so the bisection check feeds the engine the
    exact same inputs the golden saw.

    If data_loader_path is provided, polygraphy executes that Python
    file (must define load_data()) to get real face inputs. Otherwise
    polygraphy generates deterministic random inputs from --seed."""
    log(f'[probe] generating ORT golden at batch={opt_batch}'
        + (' (real face inputs)' if data_loader_path else ' (random inputs)'))
    cmd = [
        _polygraphy_exe(), 'run',
        str(patched_onnx_path),
        '--onnxrt',
        '--save-inputs',  str(inputs_path),
        '--save-outputs', str(outputs_path),
    ]
    if data_loader_path is not None:
        cmd += ['--data-loader-script', str(data_loader_path)]
    else:
        cmd += [
            '--input-shapes',
            f'target:[{opt_batch},3,128,128]',
            f'source:[{opt_batch},512]',
            '--seed', '42',
        ]
    subprocess.run(cmd, check=True)
    for p in (inputs_path, outputs_path):
        if not p.is_file():
            raise RuntimeError(f'Polygraphy did not produce {p}')


def _validate_check_setup(patched_onnx: Path, inputs: Path, outputs: Path,
                          workdir: Path, rtol: float, atol: float,
                          opt_batch: int, log) -> None:
    """Build a pure-FP32 TRT engine for the patched ONNX and run the
    same comparison the bisection check will use. If this fails, the
    check is misconfigured (wrong shapes, tolerance too strict, etc.)
    and the bisection has no chance of passing — fail fast with a
    diagnostic rather than burning 30 minutes."""
    log('[probe] pre-flight: building FP32 baseline + running check')
    poly = _polygraphy_exe()
    min_shapes = ['target:[1,3,128,128]', 'source:[1,512]']
    opt_shapes = [f'target:[{opt_batch},3,128,128]', f'source:[{opt_batch},512]']
    max_shapes = ['target:[16,3,128,128]', 'source:[16,512]']
    baseline_engine = workdir / 'baseline_fp32.engine'

    # Build FP32 engine via polygraphy convert.
    build_cmd = [
        poly, 'convert', str(patched_onnx),
        '--convert-to', 'trt',
        '-o', str(baseline_engine),
        '--trt-min-shapes', *min_shapes,
        '--trt-opt-shapes', *opt_shapes,
        '--trt-max-shapes', *max_shapes,
    ]
    log('[probe] baseline build: ' + ' '.join(build_cmd))
    subprocess.run(build_cmd, check=True)
    if not baseline_engine.is_file():
        raise RuntimeError('baseline FP32 engine build failed')

    # Run the check against the baseline.
    check_cmd = [
        poly, 'run', str(baseline_engine), '--trt',
        '--load-inputs', str(inputs),
        '--load-outputs', str(outputs),
        '--rtol', str(rtol), '--atol', str(atol),
    ]
    log('[probe] baseline check: ' + ' '.join(check_cmd))
    rc = subprocess.run(check_cmd).returncode
    if rc != 0:
        raise RuntimeError(
            'Baseline FP32 check failed (exit=%d). Even a pure-FP32 TRT '
            'engine does not match ORT within rtol=%g atol=%g — the '
            'tolerance is too strict, or the check inputs/outputs are '
            'misaligned. Try --rtol 0.05 --atol 0.05.' % (rc, rtol, atol)
        )
    log('[probe] pre-flight passed: FP32 TRT matches ORT within tolerance')


def _bisect(patched_onnx: Path, inputs: Path, outputs: Path, workdir: Path,
            rtol: float, atol: float, opt_batch: int, direction: str,
            mode: str, log) -> Path:
    """Drive polygraphy debug precision. Returns the path to the best
    surviving engine after bisection. Polygraphy sorts each iteration's
    engine into <workdir>/art/passed or .../failed based on the check
    result; we pick the most recent passed engine."""
    log(f'[probe] starting bisection (rtol={rtol}, atol={atol}, '
        f'mode={mode}, dir={direction})')
    log('[probe] this can take 10-60 minutes; each iteration is a full TRT build')

    min_shapes = ['target:[1,3,128,128]', 'source:[1,512]']
    opt_shapes = [f'target:[{opt_batch},3,128,128]', f'source:[{opt_batch},512]']
    max_shapes = ['target:[16,3,128,128]', 'source:[16,512]']
    art_dir = workdir / 'art'
    art_dir.mkdir(exist_ok=True)
    poly = _polygraphy_exe()
    # The check command polygraphy runs each iteration: build was just
    # done by the parent; here we run the resulting engine against the
    # exact same inputs ORT saw, and compare to the saved golden
    # outputs. Using --load-inputs (not --seed) avoids RNG drift
    # between polygraphy invocations.
    check_cmd = [
        poly, 'run', 'polygraphy_debug.engine', '--trt',
        '--load-inputs', str(inputs),
        '--load-outputs', str(outputs),
        '--rtol', str(rtol), '--atol', str(atol),
    ]
    cmd = [
        poly, 'debug', 'precision',
        str(patched_onnx),
        '--fp16',
        '--precision-constraints', 'obey',
        '--mode', mode,
        '--dir', direction,
        '--precision', 'float32',
        '--trt-min-shapes', *min_shapes,
        '--trt-opt-shapes', *opt_shapes,
        '--trt-max-shapes', *max_shapes,
        '--seed', '42',
        '--save-debug-replay', str(workdir / 'replay.json'),
        # Keep every iteration's engine; sort by check result so we
        # can recover the best PASSED engine even if polygraphy's own
        # convergence dropped the final artifact.
        '--no-remove-intermediate',
        '--artifacts', 'polygraphy_debug.engine',
        '--art-dir', str(art_dir),
        '--check', *check_cmd,
    ]
    log('[probe] command: ' + ' '.join(cmd))
    subprocess.run(cmd, check=True, cwd=workdir)

    # Polygraphy moves each iteration's engine into a per-result
    # subdir under art_dir. Naming varies across versions:
    #   polygraphy 0.49+  → 'good' / 'bad'
    #   earlier versions  → 'passed' / 'failed'
    # We want the most-recently-written successful engine — in
    # bisection convergence that's the final converged answer (e.g.
    # "first 941 layers in higher precision" — the smallest FP32 set
    # that still passes, i.e. the most-FP16 acceptable build).
    success_candidates = [art_dir / 'good', art_dir / 'passed']
    success_dir = next((d for d in success_candidates if d.is_dir()), None)
    if success_dir is None:
        # No iteration passed at all.
        names = ', '.join(repr(d.name) for d in success_candidates)
        raise RuntimeError(
            f'No {names} directory under {art_dir} — bisection ended '
            'without any iteration meeting the check tolerance. Try '
            '--rtol 0.05 --atol 0.05, or a different --dir / --mode.'
        )
    engines = sorted(
        success_dir.glob('*.engine'),
        key=lambda p: p.stat().st_mtime,
    )
    if not engines:
        # Fall back to a one-shot fresh polygraphy_debug.engine in cwd
        # if polygraphy named the artifacts differently.
        fallback = workdir / 'polygraphy_debug.engine'
        if fallback.is_file():
            return fallback
        raise RuntimeError(
            f'No .engine files in {success_dir}. Inspect manually.'
        )
    log(f'[probe] {len(engines)} iteration(s) passed; choosing '
        f'most-recently-built (the bisection-converged answer): '
        f'{engines[-1].name}')
    return engines[-1]


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument('--rtol', type=float, default=0.01)
    parser.add_argument('--atol', type=float, default=0.01)
    parser.add_argument('--opt-batch', type=int, default=4,
                        help='Batch size for the golden + check (default 4 = '
                             'inswapper polyphase at SwapperType=256).')
    parser.add_argument('--dir', dest='direction',
                        choices=('reverse', 'forward'), default='reverse',
                        help='Which side to start marking FP32 from. reverse '
                             '= output side (default); forward = input side. '
                             'Try forward if the inswapper sensitivity lives '
                             'in the input embedding projection.')
    parser.add_argument('--mode', choices=('bisect', 'linear'), default='bisect',
                        help='bisect = binary search (fast); linear = mark one '
                             'layer at a time (exhaustive, slow).')
    parser.add_argument('--source-img', type=str, default=None,
                        help='Path to a real source face image (e.g. ./test/b.jpg). '
                             'When set together with --target-img, the bisection '
                             'runs against real face inputs (preprocessed via '
                             'ArcFace + emap projection) instead of random uniform '
                             'data — better matches production numerics.')
    parser.add_argument('--target-img', type=str, default=None,
                        help='Path to a real target face image (e.g. ./test/a.jpg).')
    parser.add_argument('--keep-workdir', action='store_true')
    parser.add_argument('--workdir', type=str, default=None)
    args = parser.parse_args(argv)

    # Either both or neither.
    if bool(args.source_img) ^ bool(args.target_img):
        parser.error('--source-img and --target-img must be provided together')

    def log(msg: str) -> None:
        print(msg, flush=True)

    # Sanity checks before we spend any time.
    try:
        import polygraphy  # noqa: F401
    except ImportError:
        log('[probe] polygraphy not installed. Run: pip install "polygraphy>=0.49" colored')
        return 2
    try:
        from rope import TensorRTEngine as TRT
    except ImportError as e:
        log(f'[probe] failed to import rope.TensorRTEngine: {e}')
        return 2
    if not os.path.isfile(TRT.INSWAPPER_ONNX):
        log(f'[probe] {TRT.INSWAPPER_ONNX} not found — make sure the FP32 '
            'source ONNX is in the models folder')
        return 2

    workdir_ctx = None
    if args.workdir:
        workdir = Path(args.workdir)
        workdir.mkdir(parents=True, exist_ok=True)
    else:
        workdir_ctx = tempfile.TemporaryDirectory(prefix='rope_probe_fp16_')
        workdir = Path(workdir_ctx.name)
    log(f'[probe] workdir: {workdir}')

    try:
        # Step 1: patched ONNX → file
        patched_bytes = _patched_onnx_bytes(log)
        patched_path = workdir / 'inswapper_128.patched.onnx'
        patched_path.write_bytes(patched_bytes)
        log(f'[probe] wrote patched ONNX ({len(patched_bytes) >> 20} MB) -> {patched_path}')

        # Optional real-input data loader.
        loader_path: Path | None = None
        if args.source_img and args.target_img:
            for label, p in (('--source-img', args.source_img),
                             ('--target-img', args.target_img)):
                if not os.path.isfile(p):
                    log(f'[probe] {label} not found: {p}')
                    return 2
            arcface_onnx = os.path.join(
                os.path.dirname(TRT.INSWAPPER_ONNX), 'w600k_r50.onnx'
            )
            if not os.path.isfile(arcface_onnx):
                log(f'[probe] ArcFace ONNX missing at {arcface_onnx} — '
                    'required to compute the source embedding for real-input '
                    'preprocessing')
                return 2
            loader_path = workdir / 'real_data_loader.py'
            _write_data_loader(
                loader_path,
                source_img=args.source_img,
                target_img=args.target_img,
                inswapper_onnx=TRT.INSWAPPER_ONNX,
                arcface_onnx=arcface_onnx,
                batch=args.opt_batch,
            )
            log(f'[probe] wrote real-input data loader -> {loader_path}')

        # Step 2: ORT golden — save BOTH inputs and outputs.
        golden_inputs = workdir / 'golden_inputs.json'
        golden_outputs = workdir / 'golden_outputs.json'
        _generate_golden(patched_path, golden_inputs, golden_outputs,
                         args.opt_batch, loader_path, log)

        # Step 2b: pre-flight — make sure the check setup actually
        # passes against a pure-FP32 baseline before we spend hours
        # bisecting layers we don't need to.
        _validate_check_setup(patched_path, golden_inputs, golden_outputs,
                              workdir, args.rtol, args.atol,
                              args.opt_batch, log)

        # Step 3: polygraphy bisect
        final_engine = _bisect(patched_path, golden_inputs, golden_outputs,
                               workdir, args.rtol, args.atol,
                               args.opt_batch, args.direction, args.mode, log)

        # Step 4: copy to target
        log(f'[probe] copying {final_engine} -> {TRT.INSWAPPER_ENGINE}')
        shutil.copy2(final_engine, TRT.INSWAPPER_ENGINE)
        size_mb = os.path.getsize(TRT.INSWAPPER_ENGINE) >> 20
        log(f'[probe] success — installed mixed-precision engine ({size_mb} MB)')
        log('[probe] NOTE: clicking "Build TensorRT" in the UI will rebuild '
            'this engine as full-FP32. Re-run this script to get FP16 back.')
        return 0
    finally:
        if workdir_ctx is not None and not args.keep_workdir:
            workdir_ctx.cleanup()
        elif args.keep_workdir:
            log(f'[probe] kept workdir at {workdir}')


if __name__ == '__main__':
    sys.exit(main())
