DEFAULT_DATA = {
# Buttons
'AddMarkerButtonDisplay':           'icon',
'AddMarkerButtonIconHover':            './rope/media/add_marker_hover.png',    
'AddMarkerButtonIconOff':              './rope/media/add_marker_off.png',
'AddMarkerButtonIconOn':               './rope/media/add_marker_off.png',
'AddMarkerButtonInfoText':             'ADD MARKER:\nAttaches a parameter marker to the current frame. Markers copy all parameter settings and apply them to all future frames, or until another marker is encountered.',
'AddMarkerButtonState':           False,
'AudioDisplay':             'text', 
'AudioInfoText':             'ENABLE REAL-TIME AUDIO:\nAdds audio from the input video during preview playback. If you are unable to maintain the input video frame rate, the audio will lag.',   
'AudioState':               False,
'AudioText':                'Enable Audio',      
'AutoSwapState':            False,
'ClearFacesDisplay':        'text', 
'ClearFacesIcon':            './rope/media/tarfacedel.png',
'ClearFacesIconHover':      './rope/media/rec.png',
'ClearFacesIconOff':        './rope/media/rec.png',
'ClearFacesIconOn':         './rope/media/rec.png',
'ClearFacesInfoText':             'REMOVE FACES:\nRemove all currently found faces.',
'ClearFacesState':          False,      
'ClearFacesText':           'Clear Faces',
'DefaultParamsButtonDisplay':           'text',
'DefaultParamsButtonInfoText':             'LOAD DEFAULT PARAMETERS:\nLoad the Rope default parameters for this column.',
'DefaultParamsButtonState':           False,
'DefaultParamsButtonText':           'Load Defaults',
'DelEmbedDisplay':          'text', 
'DelEmbedIconHover':        './rope/media/rec.png',      
'DelEmbedIconOff':          './rope/media/rec.png',
'DelEmbedIconOn':           './rope/media/rec.png',
'DelEmbedInfoText':             'DELETE EMBEDDING:\nDelete the currently selected embedding',
'DelEmbedState':            False,          
'DelEmbedText':             'Delete Emb',  
'DelMarkerButtonDisplay':           'icon',
'DelMarkerButtonIconHover':            './rope/media/remove_marker_hover.png',    
'DelMarkerButtonIconOff':              './rope/media/remove_marker_off.png',
'DelMarkerButtonIconOn':               './rope/media/remove_marker_off.png',
'DelMarkerButtonInfoText':             'REMOVE MARKER:\nRemoves the parameter marker from the current frame.',
'DelMarkerButtonState':           False,
'FindFacesDisplay':         'text', 
'FindFacesIcon':         './rope/media/tarface.png',
'FindFacesIconHover':       './rope/media/rec.png',
'FindFacesIconOff':         './rope/media/rec.png',
'FindFacesIconOn':          './rope/media/rec.png',
'FindFacesInfoText':             'FIND FACES:\nFinds all new faces in the current frame.',
'FindFacesState':           False,  
'FindFacesText':            'Find Faces',  
'ImgDockState':             False,
'LoadParamsButtonDisplay':           'text',
'LoadParamsButtonInfoText':             'LOAD SAVED PARAMETERS:\nLoads all parameters from this column if they have been previously saved. ',
'LoadParamsButtonState':           False,
'LoadParamsButtonText':           'Load Params',
'LoadSFacesDisplay':         'both', 
'LoadSFacesIcon':            './rope/media/save.png',
'LoadSFacesIconHover':        './rope/media/save.png',     
'LoadSFacesIconOff':          './rope/media/save.png',
'LoadSFacesIconOn':           './rope/media/save.png',
'LoadSFacesInfoText':             'SELECT SOURCE FACES FOLDER:\nSelects and loads Source Faces from Folder. Make sure the folder only contains <good> images.',
'LoadSFacesState':          False,
'LoadSFacesText':           'Select Faces Folder',  
'LoadTVideosDisplay':         'both', 
'LoadTVideosIconHover':        './rope/media/save.png', 
'LoadTVideosIconOff':          './rope/media/save.png',
'LoadTVideosIconOn':           './rope/media/save.png',
'LoadTVideosInfoText':             'SELECT INPUT VIDEOS/IMAGES FOLDER:\nSelect and load media from folder.',
'LoadTVideosState':         False,    
'LoadTVideosText':           'Select Media Folder',
'MaskViewDisplay':         'text',   
'MaskViewInfoText':             'SHOW MASKS:\nDisplays the mask for a face side-by-side with the face. Useful for understanding the masking behaviors and results.',
'MaskViewState':            False,    
'MaskViewText':           'Show Mask', 
'NextMarkerButtonDisplay':           'icon',
'NextMarkerButtonIconHover':            './rope/media/next_marker_hover.png',    
'NextMarkerButtonIconOff':              './rope/media/next_marker_off.png',
'NextMarkerButtonIconOn':               './rope/media/next_marker_off.png',
'NextMarkerButtonInfoText':             'NEXT MARKER:\nMove to the next marker.',
'NextMarkerButtonState':           False,
'OutputFolderDisplay':         'both',
'OutputFolderIconHover':        './rope/media/save.png',
'OutputFolderIconOff':          './rope/media/save.png',
'OutputFolderIconOn':           './rope/media/save.png',
'OutputFolderInfoText':             'SELECT SAVE FOLDER:\nSelect folder for saved videos and images.',
'OutputFolderState':        False,
'OutputFolderText':           'Select Output Folder',

'EmbedFileDisplay':             'both',
'EmbedFileIconHover':           './rope/media/save.png',
'EmbedFileIconOff':             './rope/media/save.png',
'EmbedFileIconOn':              './rope/media/save.png',
'EmbedFileInfoText':            'SELECT EMBEDDING FILE:\nSelect the .txt file used to read and write merged embeddings. Defaults to merged_embeddings.txt in the working directory.',
'EmbedFileState':               False,
'EmbedFileText':                'Select Embedding File',
'PlayDisplay':              'icon',
'PlayIconHover':            './rope/media/play_hover.png',
'PlayIconOff':              './rope/media/play_off.png',
'PlayIconOn':               './rope/media/play_on.png',
'PlayInfoText':             'PLAY:\nPlays the video. Press again to stop playing',
'PlayState':                False,
'PrevMarkerButtonDisplay':           'icon',
'PrevMarkerButtonIconHover':            './rope/media/previous_marker_hover.png',    
'PrevMarkerButtonIconOff':              './rope/media/previous_marker_off.png',
'PrevMarkerButtonIconOn':               './rope/media/previous_marker_off.png',
'PrevMarkerButtonInfoText':             'PREVIOUS MARKER:\nMove to the previous marker.',
'PrevMarkerButtonState':           False,
'RecordDisplay':            'icon',     
'RecordIconHover':          './rope/media/rec_hover.png',
'RecordIconOff':            './rope/media/rec_off.png',
'RecordIconOn':             './rope/media/rec_on.png',
'RecordInfoText':             'RECORD:\nArms the PLAY button for recording. Press RECORD, then PLAY to record. Press PLAY again to stop recording.',  
'RecordState':              False,       
'SaveImageState':           False,
'SaveParamsButtonDisplay':           'text',
'SaveParamsButtonInfoText':             'SAVE PARAMETERS:\nSaves all parameters in this column.',
'SaveParamsButtonState':            False,
'SaveParamsButtonText':             'Save Params',
'StartRopeDisplay':                 'both', 
'StartRopeIconHover':               './rope/media/rope.png',    
'StartRopeIconOff':                 './rope/media/rope.png',
'StartRopeIconOn':                  './rope/media/rope.png',
'StartRopeInfoText':                'STARTS ROPE:\nStarts up the Rope application.',
'StartRopeState':                   False,    
'StartRopeText':                    'Start Rope',  
'SwapFacesDisplay':                 'text', 
'SwapFacesInfoText':                'SWAP:\nSwap assigned Source Faces and Target Faces.',
'SwapFacesState':                   False,          
'SwapFacesText':                    'Swap Faces',  
'TLBeginningDisplay':              'icon', 
'TLBeginningIconHover':            './rope/media/tl_beg_hover.png',
'TLBeginningIconOff':              './rope/media/tl_beg_off.png',
'TLBeginningIconOn':               './rope/media/tl_beg_on.png',
'TLBeginningInfoText':             'TIMELINE START:\nMove the timeline handle to the first frame.',
'TLBeginningState':                 False,
'TLLeftDisplay':                    'icon',   
'TLLeftIconHover':                  './rope/media/tl_left_hover.png',
'TLLeftIconOff':                    './rope/media/tl_left_off.png',
'TLLeftIconOn':                     './rope/media/tl_left_on.png',
'TLLeftInfoText':                   'TIMELEFT NUDGE LEFT:\nMove the timeline handle to the left 30 frames.',
'TLLeftState':                      False,
'TLRightDisplay':                   'icon',   
'TLRightIconHover':                 './rope/media/tl_right_hover.png',    
'TLRightIconOff':                   './rope/media/tl_right_off.png',
'TLRightIconOn':                    './rope/media/tl_right_on.png',
'TLRightInfoText':                  'TIMELEFT NUDGE RIGHT:\nMove the timeline handle to the RIGHT 30 frames.',
'TLRightState':                     False,

'SaveImageButtonDisplay':                   'text',   
'SaveImageButtonInfoText':                  'SAVE IMAGE:\nSaves the current image to your Output Folder.',
'SaveImageButtonState':                     False,
'SaveImageButtonText':             'Save Image',

'AutoSwapButtonDisplay':                   'text',   
'AutoSwapButtonInfoText':                  'AUTOSWAP:\nAutomatcially applies your currently selected Input Face to new images.',
'AutoSwapButtonState':                     False,
'AutoSwapButtonText':             'Auto Swap',
 
'ClearVramButtonDisplay':                   'text',
'ClearVramButtonInfoText':                  'CLEAR VRAM:\nClears models from your VRAM.',
'ClearVramButtonState':                     False,
'ClearVramButtonText':             'Clear VRAM',


'BenchmarkButtonDisplay':                  'text',
'BenchmarkButtonInfoText':                 'BENCHMARK:\nPlays the current video at maximum speed (no audio/wall-clock sync) using the current settings and model. Stops on user click, end-of-video, or stop-marker. Prints mean per-frame generation time (decode-pull to display) and total elapsed time to the console.',
'BenchmarkButtonState':                    False,
'BenchmarkButtonText':                     'Benchmark',

'BenchmarkHeadlessButtonDisplay':          'text',
'BenchmarkHeadlessButtonInfoText':         'BENCHMARK (HEADLESS):\nSame as Benchmark, but skips the preview-publish step — finished frames are counted and dropped instead of uploaded to the GL preview and painted. Removes display rendering from the wall-clock so the benchmark reflects swap throughput alone. Useful for telling whether the preview path is the bottleneck (compare to plain Benchmark).',
'BenchmarkHeadlessButtonState':            False,
'BenchmarkHeadlessButtonText':             'Benchmark (Headless)',

'GetNewEmbButtonDisplay':                   'text',
'GetNewEmbButtonInfoText':                  'CLEAR VRAM:\nClears models from your VRAM.',
'GetNewEmbButtonState':                     False,
'GetNewEmbButtonText':             'Clear VRAM',

'CapturePlayButtonDisplay':                 'text',
'CapturePlayButtonInfoText':                'CAPTURE PLAY/PAUSE:\nStart or stop the live screen-capture loop. The capture region is whatever sits inside the magenta viewfinder popup. While playing, captured frames go through the normal swap pipeline and the result lands in the main preview pane.',
'CapturePlayButtonState':                   False,
'CapturePlayButtonText':                    'Play',

'CaptureReopenButtonDisplay':               'text',
'CaptureReopenButtonInfoText':              'REOPEN VIEWFINDER:\nIf the viewfinder popup was closed (X-clicked), this button reopens it without leaving Capture mode.',
'CaptureReopenButtonState':                 False,
'CaptureReopenButtonText':                  'Reopen Viewfinder',

'CaptureFPSSliderAmount':                   30,
'CaptureFPSSliderInc':                      1,
'CaptureFPSSliderInfoText':                 'CAPTURE TARGET FPS:\nUpper bound on capture rate. Actual fps caps at swap throughput, which is usually well below 60. 30 is a sane default; raise on very fast GPUs, lower for less CPU load.',
'CaptureFPSSliderMax':                      60,
'CaptureFPSSliderMin':                      10,

'CaptureBorderSliderAmount':                4,
'CaptureBorderSliderInc':                   1,
'CaptureBorderSliderInfoText':              'VIEWFINDER BORDER (px):\nThickness of the colored border around the transparent capture region. The border is the only draggable surface on the popup, so making it too thin (1-2 px) is hard to grab; too thick (>10 px) eats into the captured area.',
'CaptureBorderSliderMax':                   10,
'CaptureBorderSliderMin':                   1,

'CaptureLockRegionSwitchInfoText':          'LOCK CAPTURE REGION:\nFreeze the viewfinder geometry. Drag/resize is suppressed so accidental nudges don`t shift the capture rect mid-session.',
'CaptureLockRegionSwitchState':             False,

'CaptureAlwaysOnTopSwitchInfoText':         'VIEWFINDER ALWAYS-ON-TOP:\nKeep the viewfinder above other windows so clicking another app doesn`t hide the capture region.',
'CaptureAlwaysOnTopSwitchState':            True,

'StopMarkerButtonnDisplay':                   'icon',
'StopMarkerButtonIconHover':            './rope/media/previous_marker_hover.png',
'StopMarkerButtonIconOff':              './rope/media/previous_marker_off.png',
'StopMarkerButtonIconOn':               './rope/media/previous_marker_off.png',
'StopMarkerButtonInfoText':                  'CLEAR VRAM:\nClears models from your VRAM.',
'StopMarkerButtonState':                     False,
'StopMarkerButtonText':             'Clear VRAM',
 
#Switches       
'ColorSwitchInfoText':              'RGB ADJUSTMENT:\nFine-tune the RGB color values of the swap.',
'ColorSwitchState':                 False,
'DiffSwitchInfoText':               'DIFFERENCER:\nAllow some of the original face to show in the swapped result when the difference between the two images is small. Can help bring back some texture to the swapped face',
'DiffSwitchState':                  False,
'FaceAdjSwitchInfoText':            'KPS and SCALE ADJUSTMENT:\nThis is an experimental feature to perform direct adjustments to the face landmarks found by the detector. There is also an option to adjust the scale of the swapped face.',
'FaceAdjSwitchState':               False,
'FaceParserSwitchInfoText':         'BACKGROUND MASK:\nAllow the unprocessed background from the orginal image to show in the final swap.',
'FaceParserSwitchState':            False,
'MouthParserSwitchInfoText':        'MOUTH MASK:\nAllow the mouth from the original face to show on the swapped face.',
'MouthParserSwitchState':           False,
'OccluderSwitchInfoText':           'OCCLUSION MASK:\nAllow objects occluding the face to show up in the swapped image.',
'OccluderSwitchState':              False,
'DFLXSegSwitchInfoText':            'DEEPFACELAB XSEG MASK:\nApply a DeepFaceLab-trained XSeg occlusion model (models/dfl_xseg.onnx) so objects in front of the face show through the swap.',
'DFLXSegSwitchState':               False,
'OrientSwitchInfoText':             'ORIENTATION:\nRotate the face detector to better detect faces at different angles',
'OrientSwitchState':                False,

'OrientAutoSwitchInfoText':         'AUTO ORIENTATION:\nDetect face orientation automatically. On the first frame of a video (and whenever detection fails for several frames) the detector is probed at 0/90/180/270; the winning rotation is cached for subsequent frames. Fine-tuned per-frame from the detected eye axis. Overrides the manual Orientation slider when on.',
'OrientAutoSwitchState':            False,
'RestorerSwitchInfoText':           'FACE RESTORER:\nRestore the swapped image by upscaling.',
'RestorerSwitchState':              False,
'StrengthSwitchInfoText':           'SWAPPER STRENGTH:\nApply additional swapping iterations to increase the strength of the result, which may increase likeness',
'StrengthSwitchState':              False,
'ColorMatchSwitchInfoText':         'COLOR MATCH (LAB):\nReinhard mean/std color transfer in LAB space from the pre-swap target crop to the swap output. Corrects the inswapper_128 blue/purple cast without filtering or softening detail. Applied after resize, before the manual color sliders.',
'ColorMatchSwitchState':            False,

'LikenessSliderAmount':             100,
'LikenessSliderInc':                5,
'LikenessSliderInfoText':           'LIKENESS:\nScales the swapper conditioning latent before inference (post-emap, post-normalize). >100 pushes the model harder toward the source identity (sharper likeness; >130 risks waxy / over-sharpened artifacts). 100 = unmodified, model default. Free at inference — tuning knob over the inswapper_128 identity gap.',
'LikenessSliderMax':                150,
'LikenessSliderMin':                50,

'EmbExtrapSliderAmount':            0,
'EmbExtrapSliderInc':               5,
'EmbExtrapSliderInfoText':          'DISTINCTIVENESS:\nPushes the source embedding away from the session-wide mean of loaded source faces before passing to the swapper. Amplifies what makes this face distinct from the average. 0 = no extrapolation. >50 emphasizes distinctive features (might exaggerate quirks). Mean is computed from the source-faces panel as embeddings get loaded — needs at least 2 source faces to take effect. Free at inference.',
'EmbExtrapSliderMax':               100,
'EmbExtrapSliderMin':               0,

'HighFidelitySwitchInfoText':       'HIGH FIDELITY:\nMeasures the identity gap of the swap output via ArcFace and corrects the source embedding to close it. See HF Mode for cost/quality tradeoff. Stacks with Likeness / Distinctiveness.',
'HighFidelitySwitchState':          False,
'HighFidelityAlphaSliderAmount':    50,
'HighFidelityAlphaSliderInc':       10,
'HighFidelityAlphaSliderInfoText':  'HIGH FIDELITY CORRECTION:\nHow hard to push the embedding back toward the source. 0 = no correction (effectively disables HF). 50 = half-correction (safe default). 100 = full correction (may overshoot identity). Only used when High Fidelity is on.',
'HighFidelityAlphaSliderMax':       100,
'HighFidelityAlphaSliderMin':       0,
'HighFidelityModeTextSelInfoText':  'HIGH FIDELITY MODE:\nCached (default): measure the identity gap once per target face on the first frame, then reuse it as a single-pass correction. Cheap enough for live playback.\nPer-frame: re-measure and 2-pass every frame (legacy behavior). Higher cost; useful for A/B comparison against Cached.',
'HighFidelityModeTextSelMode':      'Cached',
'HighFidelityModeTextSelModes':     ['Cached', 'Per-frame'],

'HFRefineButtonDisplay':            'text',
'HFRefineButtonInfoText':           'HF REFINE CACHE:\nMeasure the identity gap on the current frame and blend it into each target face\'s cached HF correction (running mean). Use to add more sample frames to the cache and reduce per-frame measurement noise. Only meaningful in Cached mode with High Fidelity on.',
'HFRefineButtonState':              False,
'HFRefineButtonText':               'Refine',

'HFClearCacheButtonDisplay':        'text',
'HFClearCacheButtonInfoText':       'HF CLEAR CACHE:\nDrop all cached HF identity-gap corrections for every target face. Next frame after this will re-bootstrap the cache (one 2-pass swap, then back to single-pass).',
'HFClearCacheButtonState':          False,
'HFClearCacheButtonText':           'Clear',

# Sliders
'BlendSliderAmount':                5,
'BlendSliderInc':                   1,  
'BlendSliderInfoText':              'BLEND:\nCombined masks blending distance. Is not applied to the border masks.',
'BlendSliderMax':                   100,
'BlendSliderMin':                   0,
'BorderBlurSliderAmount':           10,
'BorderBlurSliderInc':              1,  
'BorderBlurSliderInfoText':         'BORDER MASK BLEND:\nBorder mask blending distance.',
'BorderBlurSliderMax':              64,
'BorderBlurSliderMin':              0,
'BorderBottomSliderAmount':         10, 
'BorderBottomSliderInc':            1,  
'BorderBottomSliderInfoText':       'BOTTOM BORDER DISTANCE:\nA rectangle with adjustable top, bottom, and sides that blends the swapped face rseult back into the original image.',
'BorderBottomSliderMax':            64,
'BorderBottomSliderMin':            0,
'BorderSidesSliderAmount':          10, 
'BorderSidesSliderInc':             1,  
'BorderSidesSliderInfoText':        'SIDES BORDER DISTANCE:\nA rectangle with adjustable top, bottom, and sides that blends the swapped face result back into the original image.',
'BorderSidesSliderMax':             64,
'BorderSidesSliderMin':             0,
'BorderTopSliderAmount':            10, 
'BorderTopSliderInc':               1, 
'BorderTopSliderInfoText':          'TOP BORDER DISTANCE:\nA rectangle with adjustable top, bottom, and sides that blends the swapped face result back into the original image.',
'BorderTopSliderMax':               64,
'BorderTopSliderMin':               0,
'ColorBlueSliderAmount':            0,
'ColorBlueSliderInc':               1,  
'ColorBlueSliderInfoText':          'RGB BLUE ADJUSTMENT',
'ColorBlueSliderMax':               100,
'ColorBlueSliderMin':               -100,
'ColorGreenSliderAmount':           0,
'ColorGreenSliderInc':              1, 
'ColorGreenSliderInfoText':         'RGB GREEN ADJUSTMENT',
'ColorGreenSliderMax':              100,
'ColorGreenSliderMin':              -100,
'ColorRedSliderAmount':             0,
'ColorRedSliderInc':                1,
'ColorRedSliderInfoText':           'RGB RED ADJUSTMENT',
'ColorRedSliderMax':                100,
'ColorRedSliderMin':                -100,
'DetectScoreSliderAmount':          50,
'DetectScoreSliderInc':             1,      
'DetectScoreSliderInfoText':        'DETECTION SCORE LIMIT:\nDetermines the minimum score required for a face to be detected. Higher values require higher quality faces. E.g., if faces are flickering when at extreme angles, raising this will limit swapping attempts.',
'DetectScoreSliderMax':             100,
'DetectScoreSliderMin':             1,
'DiffSliderAmount':                 4,   
'DiffSliderInc':                    1,
'DiffSliderInfoText':               'DIFFERENCING AMOUNT:\nHigher values relaxes the similarity constraint.',
'DiffSliderMax':                    100,
'DiffSliderMin':                    0,
'FaceParserSliderAmount':           0,   
'FaceParserSliderInc':              1,        
'FaceParserSliderInfoText':         'BACKGROUND MASK AMOUNT:\nNegative/Positive values shrink and grow the mask.',
'FaceParserSliderMax':              50,
'FaceParserSliderMin':              -50,
'FaceScaleSliderAmount':            0,
'FaceScaleSliderInc':               1,    
'FaceScaleSliderInfoText':          'FACE SCALE AMOUNT',
'FaceScaleSliderMax':               20,
'FaceScaleSliderMin':               -20,
'KPSScaleSliderAmount':             0, 
'KPSScaleSliderInc':                1,  
'KPSScaleSliderInfoText':           'KPS SCALE AMOUNT:\nGrows and shrinks the detection point distances.',
'KPSScaleSliderMax':                100,
'KPSScaleSliderMin':                -100,
'KPSXSliderAmount':                 0, 
'KPSXSliderInc':                    1,      
'KPSXSliderInfoText':               'KPS X-DIRECTION AMOUNT:\nShifts the detection points left and right',
'KPSXSliderMax':                    100,
'KPSXSliderMin':                    -100,
'KPSYSliderAmount':                 0, 
'KPSYSliderInc':                    1,  
'KPSYSliderInfoText':               'KPS Y-DIRECTION AMOUNT:\nShifts the detection points lup and down',
'KPSYSliderMax':                    100,
'KPSYSliderMin':                    -100,
'MouthParserSliderAmount':          0, 
'MouthParserSliderInc':             1,      
'MouthParserSliderInfoText':        'MOUTH MASK AMOUNT:\nAdjust the size of the mask. Negative values only mask the inside of the mouth, including the tongue. Positive values also include lips',
'MouthParserSliderMax':             50,
'MouthParserSliderMin':             -50,
'OccluderSliderAmount':             0,
'OccluderSliderInc':                1,
'OccluderSliderInfoText':           'OCCLUDER AMOUNT:\nGrows or shrinks the occluded region',
'OccluderSliderMax':                100,
'OccluderSliderMin':                -100,
'DFLXSegSizeSliderAmount':          0,
'DFLXSegSizeSliderInc':             1,
'DFLXSegSizeSliderInfoText':        'XSEG MASK SIZE:\nNegative/Positive values shrink and grow the masked region.',
'DFLXSegSizeSliderMax':             100,
'DFLXSegSizeSliderMin':             -100,
'DFLXSegBlurSliderAmount':          0,
'DFLXSegBlurSliderInc':             1,
'DFLXSegBlurSliderInfoText':        'XSEG MASK BLUR:\nSoftens the edge of the XSeg mask.',
'DFLXSegBlurSliderMax':             50,
'DFLXSegBlurSliderMin':             0,
'OrientSliderAmount':               0,
'OrientSliderInc':                  90,
'OrientSliderInfoText':             'ORIENTATION ANGLE:\nSet this to the angle of the input face angle to help with laying down/upside down/etc. Angles are read clockwise.',
'OrientSliderMax':                  270,
'OrientSliderMin':                  0,
'RestorerSliderAmount':             100,
'RestorerSliderInc':                5,
'RestorerSliderInfoText':           'RESTORER AMOUNT:\nBlends the Restored results back into the original swap.',
'RestorerSliderMax':                100,
'RestorerSliderMin':                0,
'StrengthSliderAmount':             100,
'StrengthSliderInc':                25,    
'StrengthSliderInfoText':           'STRENGTH AMOUNT:\nIncrease up to 5x additional swaps (500%). 200% is generally a good result. Set to 0 to turn off swapping but allow the rest of the pipeline to apply to the original image.',
'StrengthSliderMax':                500,
'StrengthSliderMin':                0,
'ThreadsSliderAmount':              5,
'ThreadsSliderInc':                 1,    
'ThreadsSliderInfoText':            'EXECUTION THREADS:\nSet number of execution threads while playing and recording. Depends strongly on GPU VRAM. 5 threads for 24GB.',
'ThreadsSliderMax':                 20,
'ThreadsSliderMin':                 1,
'ThresholdSliderAmount':            55,
'ThresholdSliderInc':               1,
'ThresholdSliderInfoText':          'THRESHHOLD AMOUNT:\nRaise to reduce faces hopping around when swapping multiple people. A higher value is stricter.',
'ThresholdSliderMax':               100,
'ThresholdSliderMin':               0,
'VideoQualSliderAmount':            18,
'VideoQualSliderInc':               1,      
'VideoQualSliderInfoText':          'VIDEO QUALITY:\nThe encoding quality of the recorded video. 0 is best, 50 is worst, 18 is mostly lossless. File size increases with a lower quality number.',
'VideoQualSliderMax':               50,
'VideoQualSliderMin':               0,

'ColorGammaSliderAmount':                 1,
'ColorGammaSliderInc':                    0.01,
'ColorGammaSliderInfoText':               'GAMMA VALUE:\nChanges Gamma.',
'ColorGammaSliderMax':                    2,
'ColorGammaSliderMin':                    0,

'ColorContrastSliderAmount':                 1,
'ColorContrastSliderInc':                    0.01,
'ColorContrastSliderInfoText':               'CONTRAST VALUE:\nChanges Contrast.',
'ColorContrastSliderMax':                    2.0,
'ColorContrastSliderMin':                    0.0,

'ColorSaturationSliderAmount':                 1,
'ColorSaturationSliderInc':                    0.01,
'ColorSaturationSliderInfoText':               'SATURATION VALUE:\nChanges Saturation.',
'ColorSaturationSliderMax':                    2,
'ColorSaturationSliderMin':                    0,

'FindSimilarFacesButtonDisplay':            'text',
'FindSimilarFacesButtonInfoText':           'FIND SIMILAR FACES:\nN^2 compare every folder face against every other. Each face\'s score is the smallest max-axis embedding difference to any other face (lower = more similar). Faces are reordered ascending and labeled with their score; faces above the threshold slider are dimmed.',
'FindSimilarFacesButtonState':              False,
'FindSimilarFacesButtonText':               'Find Similar',

'FindSimilarThresholdSliderAmount':         1.0,
'FindSimilarThresholdSliderInc':            0.01,
'FindSimilarThresholdSliderInfoText':       'FIND SIMILAR THRESHOLD:\nMaximum allowed per-axis embedding difference for a face to count as "similar" to its nearest neighbor. Embeddings here are raw (not L2-normalized), so typical scores fall in the 0.5 – 5.0 range. Faces with score above the threshold are dimmed in the panel; faces at or below are highlighted.',
'FindSimilarThresholdSliderMax':            5,
'FindSimilarThresholdSliderMin':            0,


# Text Selection
'DetectTypeTextSelInfoText':        'FACE DETECTION MODEL:\nSelect the face detection model. Mostly only subtle differences, but can significant differences when the face is at extreme angles or covered.',
'DetectTypeTextSelMode':            'Retinaface',
'DetectTypeTextSelModes':           ['Retinaface', 'SCRDF'],

'DetectInputSizeTextSelInfoText':   'DETECT INPUT SIZE:\nResolution the detector is fed (square). 640 is the original / safest — catches small faces and profiles well. 480 ≈ 1.8x faster, still solid for talking-head content. 416 ≈ 2.4x. 320 ≈ 4x faster but starts missing faces below ~36 px in the source frame. Applies to all detector modes (Retinaface, SCRDF). No effect on swap quality, only what gets found in the first place.',
'DetectInputSizeTextSelMode':       '640',
'DetectInputSizeTextSelModes':      ['320', '416', '480', '640'],

'ModelSessionsTextSelInfoText':     'MODEL SESSIONS:\nControls how every ORT-TRT-EP model session in the swap pipeline (inswapper, inswapper_512, retinaface, recognition) is shared across worker threads.\n\nShared — one session per model, used by all workers. Lowest VRAM, but workers serialize inside ORT on each session\'s internal state (4 threads ≈ 2x speedup instead of 4x at the inswapper call).\n\nPer-Thread — each worker gets its own session per model. True parallel model runs (4 threads ≈ 4x speedup at dim=2/4) and torch+ORT share a CUDA stream via user_compute_stream so the syncvec drain is skipped. Costs ~150-300 MB extra VRAM per worker per model (~600 MB-1.5 GB total at 4 workers). On-disk TRT engine cache is shared so engine build is paid once. Recommended for ≥ 12 GB VRAM.',
'ModelSessionsTextSelMode':         'Shared',
'ModelSessionsTextSelModes':        ['Shared', 'Per-Thread'],
'PreviewModeTextSelInfoText':       '',
'PreviewModeTextSelMode':           'Video',
'PreviewModeTextSelModes':          ['Video', 'Capture'],
'RecordTypeTextSelInfoText':        'VIDEO RECORDING LIBRARY:\nSelect the recording library used for video recording. FFMPEG uses the Video Quality slider to adjust the size and quality of the final video. OPENCV has no options but is faster and produces good results.',
'RecordTypeTextSelMode':            'FFMPEG',
'RecordTypeTextSelModes':           ['FFMPEG', 'OPENCV'],
'RestorerDetTypeTextSelInfoText':   'ALIGNMENT:\nSelect how the face is aligned for the Restorer. Original preserves facial features and expressions, but can show some artifacts. Reference softens features. Blend is closer to Reference but is much faster.',
'RestorerDetTypeTextSelMode':       'Blend',
'RestorerDetTypeTextSelModes':      ['Original', 'Blend', 'Reference'],  
'RestorerTypeTextSelInfoText':      'RESTORER TYPE:\nSelect the Restorer type.\nSpeed: GPEN256>GFPGAN>CF>GPEN512',
'RestorerTypeTextSelMode':          'GFPGAN',
'RestorerTypeTextSelModes':         ['GFPGAN', 'CF', 'GPEN256', 'GPEN512'],
'MergeTextSelInfoText':      'INPUT FACES MERGE MATH:\nHow the selected faces\' 512-d embeddings are combined into one identity vector.\n\nMean — element-wise average. Standard, fastest.\nMedian — per-axis median. Robust to one bad face but the result is a synthetic mix of axes from different faces.\nSph — spherical centroid: L2-normalize each, mean, renormalize. Matches the unit-sphere geometry ArcFace was trained on; usually a small upgrade over Mean.\nGeo — geometric median (Weiszfeld). The point in embedding space minimizing total L2 distance to all inputs. More outlier-robust than Median because it stays a real point.\nQual — quality-weighted mean: weights each face by its embedding magnitude (a documented proxy for face quality from the MagFace literature). Good when input quality varies a lot.',
'MergeTextSelMode':          'Mean',
'MergeTextSelModes':         ['Mean', 'Median', 'Sph', 'Geo', 'Qual'],
'SwapperTypeTextSelInfoText':      'SWAPPER OUTPUT RESOLUTION:\nDetermines the resolution of the swapper output. 128/256/512 use the inswapper_128 model with NxN polyphase tiling; "256-Native" uses the dedicated single-pass inswapper_256_phase1 model.',
'SwapperTypeTextSelMode':          '128',
'SwapperTypeTextSelModes':         ['128', '256', '512', '256-Native'],
}

PARAMS =   {

    'AutoSwapFunction':         'self.toggle_auto_swap()',
    'SaveImageFunction':         'self.save_image()',

    'SaveImageIcon':            './rope/media/save_disk.png',
    'RefDelIcon':          './rope/media/construction.png',
    'TransformIcon':          './rope/media/scale.png',    
    'ThresholdIcon':            './rope/media/thresh.png',
    'LoadSFacesIcon':            './rope/media/save.png',
    'BorderIcon':                 './rope/media/maskup.png',
    'OccluderIcon':             './rope/media/occluder.png',
    'ColorIcon':            './rope/media/rgb.png',
    'StrengthIcon':             './rope/media/strength.png',
    'OrientationIcon':          './rope/media/orient.png',
    'DiffIcon':                 './rope/media/diff.png',
    'MouthParserIcon':           './rope/media/parse.png',
    'AudioIcon':            './rope/media/rgb.png',    
    'VideoQualityIcon':            './rope/media/tarface.png',    
    'MaskViewIcon':             './rope/media/maskblur.png',
    'BlurIcon':                 './rope/media/blur.png',    
    'ToggleStopIcon':            './rope/media/STOP.png',    
     'DelEmbedIcon':            './rope/media/delemb.png',



    'ToggleStopMessage':         'STOP MARKER - Sets a frame that will stop the video playing/recording.',
    'AutoSwapMessage':         'AUTO SWAP - Automatically swaps the first person in an image to the selcted source faces [LB: Turn on/off]',
    'SaveImageMessage':         'SAVE IMAGE - Save image to output folder',
    'RefDelMessage':       'REFERENCE DELTA - Modify the reference points. Turn on mask preview to see adjustments. [LB: on/off, RB: translate x/y, and scale, MW: amount]' ,
    'ThresholdMessage':         'THRESHOLD - Threshold for determining if Target Faces match faces in a frame. Lower is stricter. [LB: use amount/match all, MW: value]',
    'TransformMessage':       'SCALE - Adjust the scale of the face. Use with Background parser to blend into the image. [LB: on/off, MW: amount]',     
    'PlayMessage':         'PLAY - Plays the video. Press again to stop playing',  
 
     }   
     
